---
- hosts: localhost
  become: yes
  become_method: sudo
  vars:
    sequence_open: 7000,8000,9000
    sequence_close: 9000,8000,7000
    # Sequence to open/close port.
    seq_timeout: 25
    # Number of seconds sequence must be completed in.
    cmd_timeout: 120
    # Number of seconds before runing the closing command.
    interface: wlan0
    # Interface to listen, default is hardcoded eth0.
    command_open: ufw allow in on {{ interface }} from %IP% to any port 22 proto tcp 
    command_close: ufw delete allow in on {{ interface }} from %IP% to any port 22 proto tcp 
    # Commands to open/close port.
    auth: client-secrect
    port_tor: 22
    port_local: 22
  tasks:
  - name: Installing Tor and knockd
    apt: name={{ item }} state=present
    with_items:
     - tor
     - knockd
     - ufw
  
  - name: Default deny inbound traffic
    ufw: state=enabled policy=deny

  - name: Configure Knockd
    template: src=knockd.conf.j2 dest=/etc/knockd.conf
    notify:
      - Restart knockd

  - name: Enable Knockd
    lineinfile: dest=/etc/default/knockd regexp="START_KNOCKD=0" line="START_KNOCKD=1"
    notify:
      - Restart knockd

  - name: Configure Tor
    template: src=torrc.j2 dest=/etc/tor/torrc
    notify:
      - Restart Tor

  - name: Make sure Tor is running
    service: name=tor state=started enabled=yes

  - name: Make sure Knockd is running
    service: name=knockd state=started enabled=yes
    
  handlers:
    - name: Restart knockd
      service: name=knockd state=restarted
    - name: Restart Tor
      service: name=tor state=restarted